### ISSUE TITLE
How do I set the time for each cookie?

### ISSUE THREAD

**Issue by Samdyddd** [devries/bottle-session#3]
An instance has been installed.
 session['id'] = int(userInfo.id)
    session['account'] = userInfo.account
    session['accountID'] = userInfo.account_id
    session['level'] = userInfo.level
    session['lastLoginTime'] = userInfo.last_login_time

    # Seven days to login
    if autoLogin:
        # session.max_age = 7*24*60*60
        session.__init__()
        # session.SessionPlugin(cookie_lifetime=7*24*60*60)
        print session.max_age

**Comment by devries** [comment]
You can't set the cookie lifetime to be different for each cookie, but within a session you can tell it how long a login should last. For example if you set

```
session['login_expires'] = time.time()+3600.0
```

then you can check if `time.time()` is greater than `session['login_expires']` for each request they make and log them out, potentially by destroying the session cookie at that time.

**Comment by Samdyddd** [comment]
Thans a lot ,than was a big help.

**Comment by devries** [comment]
You're welcome.
